version: '3.8'

services:

    central-server:
        build:
            context: ./central-server
            dockerfile: Dockerfile
        image: centra-server
        ports:
            - 5005:5005
        volumes:
            - './central-server:/app'
            - '/app/node_modules'

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: frontend
        ports:
            - 3000:3000
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        stdin_open: true
        # tty: true

    broker-mosquitto:
      image: eclipse-mosquitto:1.6
      ports:
        - 1883:1883
        - 9001:9001
      volumes:
        - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
        - /mosquitto/data
        - /mosquitto/log